name: To create Build and Deploy to GKE of google cloud project (only for dev environment)
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Namespace to apply the changes"
        default: "none"
        type: choice
        required: true
        options:
          - "dev1"
          - "dev2"

jobs:
  maven-build:
    name: Run and generate Maven build
    runs-on: ubuntu-latest
    outputs:
      sampleOutput: "test value"
    steps:
      - name: repo/checkout
        uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.BUILD_TOKEN }} 

      - name: Get Branch details
        id: branch_name
        run: |
          branch="${{ github.ref }}"
          echo "branch="$branch >> $GITHUB_OUTPUT
          echo $branch
          echo $GITHUB_OUTPUT
  # docker-bbuild-push:


  # gke-deployment:
  
